[package]
name = "jimiru_jitaku"
version = "0.1.0"
authors = ["azyobuzin <azyobuzin@users.sourceforge.jp>"]
publish = false

[dependencies]
jimiru = { path = "../jimiru" }
native-tls = "0.1"
toml = "0.4"
serde = "1"
serde_derive = "1"
